### ISSUE TITLE
Regarding Overlay-Navbar 

### ISSUE THREAD

**Issue by shubhamhere** [meabhisingh/mernProjectEcommerce#1]
The overlay navbar does not collapse on itself when we click any link in it. Due to this we cannot know that click actually worked until we cut the overlay navbar by ourselves.

**Comment by haseebkhalid907** [comment]
show me

**Comment by haseebkhalid907** [comment]
when you host this site ..... this problem will be solved!😅

**Comment by rgautam320** [comment]
ERROR: "Query was already executed" at 7:07:00 (YouTube Video) during implementing filteredProductsCount at backend

If you are developing this project now, then you might face this error.
This is because Mongoose no longer allows executing the same query twice from version 6 onwards.
There are two solutions:
1 -> Downgrade your mongoose version in your package.json file to "mongoose": "^5.13.5" and then run `npm install`
---OR---
2 -> Call clone() method to your 2nd query like:
`const apiFeature = new ApiFeatures(Product.find(), req.query)
    .search()
    .filter();

  let products = await apiFeature.query;

  let filteredProductsCount = products.length;

  apiFeature.pagination(resultPerPage);

  products = await apiFeature.query.clone();`

**Comment by meabhisingh** [comment]
Autoclose in overlay navbar is now working, but you also have to password icons manually.
Check out this video.
https://youtu.be/rWUm844U7nI
