### ISSUE TITLE
Overlay navbar error using react-icons

### ISSUE THREAD

**Issue by zaroon427** [meabhisingh/mernProjectEcommerce#4]
ERROR in ./node_modules/react-icons/all.js 4:0-22

The requested module './io5' contains conflicting star exports for the names 'IoLogoAndroid', 'IoLogoAngular', 'IoLogoApple', 'IoLogoBitbucket', 'IoLogoBitcoin', 'IoLogoBuffer', 'IoLogoChrome', 'IoLogoClosedCaptioning', 'IoLogoCodepen', 'IoLogoCss3', 'IoLogoDesignernews', 'IoLogoDribbble', 'IoLogoDropbox', 'IoLogoEuro', 'IoLogoFacebook', 'IoLogoFlickr', 'IoLogoFoursquare', 'IoLogoGithub', 'IoLogoGoogle', 'IoLogoHackernews', 'IoLogoHtml5', 'IoLogoInstagram', 'IoLogoIonic', 'IoLogoIonitron', 'IoLogoJavascript', 'IoLogoLinkedin', 'IoLogoMarkdown', 'IoLogoNoSmoking', 'IoLogoNodejs', 'IoLogoNpm', 'IoLogoOctocat', 'IoLogoPinterest', 'IoLogoPlaystation', 'IoLogoPython', 'IoLogoReddit', 'IoLogoRss', 'IoLogoSass', 'IoLogoSkype', 'IoLogoSlack', 'IoLogoSnapchat', 'IoLogoSteam', 'IoLogoTumblr', 'IoLogoTux', 'IoLogoTwitch', 'IoLogoTwitter', 'IoLogoUsd', 'IoLogoVimeo', 'IoLogoVk', 'IoLogoWhatsapp', 'IoLogoWindows', 'IoLogoWordpress', 'IoLogoXbox', 'IoLogoXing', 'IoLogoYahoo', 'IoLogoYen', 'IoLogoYoutube' with the previous requested module './io'

**Comment by CodeAbsolute** [comment]
https://github.com/meabhisingh/mernProjectEcommerce/issues/3#issuecomment-1013628346

**Comment by manishkumar-8218** [comment]
just add react-icons@3 apart from react-icons

**Comment by iamakbarsha1** [comment]
I think this issue is related to react-icons and webpack 5. Someone has already posted a similar issue in react-icons github https://github.com/react-icons/react-icons/issues/514

and you're using create-react-app version 5 which use webpack 5 as module bundler. Nothing we can really do until react-icons updating their library regarding this (if you insist on using version 5).

Meanwhile, the easiest way you can downgrade your webpack to version 4 by downgrading create-react-app. Try this command: npm i react-scripts@4

**note: I notice too that you're using react-router-dom ^6.2.1, you should downgrade this too as overlay-navbar doesn't support that version. Try this command: npm i react-router-dom@5

**Comment by meabhisingh** [comment]
Checkout this video.
https://youtu.be/rWUm844U7nI
